vim.opt.cmdheight = 0                 -- Set command-line height to 0 lines
vim.opt.shiftwidth = 4                -- Number of spaces to use for each step of (auto)indent
vim.opt.tabstop = 4                   -- Number of spaces that a <Tab> in the file counts for
vim.opt.softtabstop = 4               -- Number of spaces that a <Tab> counts for while performing editing operations
vim.opt.expandtab = true              -- Convert tabs to spaces
vim.opt.smartindent = true            -- Autoindent new lines
vim.opt.number = true                 -- Show line numbers
vim.opt.relativenumber = true         -- Show relative line number
vim.opt.title = true                  -- Set the window title
vim.opt.termguicolors = true          -- Enable 24-bit RGB color in the TUI
vim.opt.spell = false                 -- Disable spell checking
vim.opt.ignorecase = true             -- Case insensitive searching
vim.opt.smartcase = true              -- Case sensitive search if search string contains uppercase
vim.opt.wrap = false                  -- Disable line wrapping
vim.opt.breakindent = true            -- Maintain indent when wrapping indented lines
vim.opt.linebreak = true              -- Wrap at word boundaries
vim.opt.list = true                   -- Enable the below listchars
vim.opt.listchars = { tab = '▸ ', trail = '·' } -- Characters to use in 'list' mode
vim.opt.fillchars:append({ eob = ' ' }) -- Remove the ~ from end of buffer
vim.opt.mouse = 'a'                   -- Enable mouse for all modes
vim.opt.mousemoveevent = true         -- Allow hovering in bufferline
vim.opt.splitbelow = true             -- Horizontal splits will be below
vim.opt.splitright = true             -- Vertical splits will be to the right
vim.opt.scrolloff = 8                 -- Minimum number of screen lines to keep above and below the cursor
vim.opt.sidescrolloff = 8             -- Minimum number of screen columns to keep to the left and right of the cursor
vim.opt.clipboard = 'unnamedplus'     -- Use Linux system clipboard
vim.opt.confirm = true                -- Ask for confirmation instead of erroring
vim.opt.undofile = true               -- Persistent undo
vim.opt.backup = true                 -- Automatically save a backup file
vim.opt.backupdir:remove('.')         -- Keep backups out of the current directory
vim.opt.shortmess:append({ I = true }) -- Disable the splash screen
vim.opt.wildmode = 'longest:full,full' -- Complete the longest common match, and allow tabbing the results to fully complete them
vim.opt.completeopt = 'menuone,longest,preview' -- Options for insert mode completion
vim.opt.signcolumn = 'no'          -- Always show the sign column, make room for two signs
vim.opt.showmode = false              -- Do not show the current mode
vim.opt.updatetime = 4001             -- Set updatime to 1ms longer than the default to prevent polyglot from changing it
vim.opt.redrawtime = 10000            -- Allow more time for loading syntax on large files
vim.opt.exrc = true                   -- Allow project-specific .nvimrc files
vim.opt.secure = true                 -- Disallow dangerous commands in local .nvimrc files
vim.opt.titlestring = '%f // nvim'    -- Custom format for window title

