
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"
HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
VI_MODE_SET_CURSOR=true
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true

plugins=(
    vi-mode
    git
    tmux
)

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
alias vi=nvim
alias vim=nvim
alias sail="vendor/bin/sail"
alias p="sail pest"
alias pf="sail pest --filter"

source $ZSH/oh-my-zsh.sh

setopt auto_cd
cdpath=(
    $HOME/code
)
